services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "${HOST_PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development